### ISSUE TITLE
Halo profiles typo

### ISSUE THREAD

**Issue by chrgeorgiou** [LSSTDESC/CCLX#23]
Text above cell 9 of the notebook "Halo profiles" states the self._real function must output a 2-D array of shape (n_radius, n_mass) but the docstring on the same function in cell 9 states the returned array must have shape (n_mass, n_radius) instead. I believe the second one is correct.

**Comment by elisachisari** [comment]
@damonge or @nikfilippas could you check this?

**Comment by nikfilippas** [comment]
`prof._real(cosmo, [1, 1.1], [1e13, 2e13, 1e14], 1, hmd).shape` comes out as `(3, 2)` so Chris is right and the example is wrong.
