### ISSUE TITLE
Issues with Halo Profiles.ipynb Tutorial

### ISSUE THREAD

**Issue by James11222** [LSSTDESC/CCLX#39]
Hi,

I'm new to pyccl, I'm currently interested in using the Halo Profiles module (`Halo profiles.ipynb`) of the code but a lot of it seems to be deprecated/out of date? A lot of the functions seem to have new/different syntax associated with them compared to older versions?

For example in the notebook

```python
# We will also use a mass definition with Delta = 200, and the Duffy 2008 concentration-mass relation
hmd_200c = ccl.halos.MassDef200c
cM = ccl.halos.ConcentrationDuffy08(mass_def=hmd_200c)
```

Gives me the error that `mass_def` is an unexpected keyword argument.

I think I was able to get around this by reading some documentation of that function but again there is more issues as we move down the notebook.

Another example

```python
profs = {}
profs['NFW'] = ccl.halos.HaloProfileNFW(mass_def=hmd_200c, concentration=cM, truncated=False)
```

all of these profiles give me errors because `mass_def` and `concentration` are no longer arguments. I was also able to get around this by reading documentation which states that the argument needed is actually `c_M_relation`.

The issue I'm currently stuck on which I need assistance on is

```python
for n,p in profs.items():
    rho_r = p.real(cosmo, r_arr, 1E14, a_sf)
    plt.plot(r_arr, rho_r, label=n)
```

There are several issues here. The method `.real` is now `._real`, and it's missing the `mass_def` argument, when I plugged those in and fixed that I came across 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[28], line 4
      2 plt.figure()
      3 for n,p in profs.items():
----> 4     rho_r = p._real(cosmo, r=r_arr, M=1e14, a=a_sf, mass_def=hmd_200c)
      5     plt.plot(r_arr, rho_r, label=n)
      6 plt.xscale('log')

File ~/.conda/envs/survey_cosmo/lib/python3.8/site-packages/pyccl/halos/profiles.py:694, in HaloProfileNFW._real(self, cosmo, r, M, a, mass_def)
    691 M_use = np.atleast_1d(M)
    693 # Comoving virial radius
--> 694 R_M = mass_def.get_radius(cosmo, M_use, a) / a
    695 c_M = self._get_cM(cosmo, M_use, a, mdef=mass_def)
    696 R_s = R_M / c_M

TypeError: get_radius() missing 1 required positional argument: 'a'
```
Going down the rabbit hole, that `.get_radius()` function doesn't even work because the cosmology object doesn't have a method `.get_Delta()`.

I also found that the `mass_def` type of variable `hmd_200c` for example has a `.get_Delta` method but it also breaks when putting in the documented arguments for example 

```python
hmd_200c.get_Delta(cosmo=cosmo, a=a_sf)
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[41], line 1
----> 1 hmd_200c.get_Delta(cosmo=cosmo, a=a_sf)

TypeError: get_Delta() missing 1 required positional argument: 'self'
```

I'm not sure how these functions are implemented but there also seems to be some bugs that come with new updates/implementation of modules I presume?

Needless to say, the tutorial is a bit unusable and I don't know how to dig much deeper without rewriting code in `pyccl`. Do I need to revert to an older version of the code or something? I'm using `pyccl=3.0.0` currently and just trying to run that notebook.

Any advice/help would be greatly appreciated.

Onwards,
James

**Comment by damonge** [comment]
Are you sure you're using v3.0.0 of CCL?

**Comment by James11222** [comment]
Hello,

I'm so sorry that's so embarrassing. I assumed using the command

 $ conda install -c conda-forge pyccl

would install the latest version but it installed version 2.3.0 for
some reason. That makes a lot of sense now. I'm so sorry for the
inconvenience.

Onwards,
James

**Comment by damonge** [comment]
No worries! Hope you can run things. Let us know otherwise.
